sudo: false

notifications:
  email:
    on_success: never
    on_failure: always

language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - 7
  - nightly

before_install:
  - if [ $TRAVIS_PHP_VERSION != "hhvm" && $TRAVIS_PHP_VERSION != "nightly" ]; then phpenv config-rm xdebug.ini ; fi
  - composer self-update

install:
  - composer install

script:
  - composer test
